services:
  wavesurfer-react:
    container_name: wavesurfer-react-dev
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
